artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/Nani1432/nlp_project/raw/main/summarizer-data.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_ingestion
  status_file: artifacts/data_ingestion/status.txt
  all_required_file: ['train','test','validation']


data_transformation:
  root_dir: artifacts/data_ingestion
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail